name: AulerSkywars
version: 1.0.0
author: Rafael Auler
main: me.rafaelauler.sw.Main
description: PvPRounds plugin
depend: [Vault, Multiverse-Core]
softdepend: [ItemJoin, PlaceholderAPI]

commands:
   sw:
   setswlobby:
   sw1:
   sw2:
   sw3: 
   
   
   