name: AulerSkywars
version: 1.0.0
author: Rafael Auler
main: me.rafaelauler.sw.Main
description: Simple skywars plugin
depend: [Vault, Multiverse-Core]
load: POSTWORLD
softdepend: [ItemJoin, PlaceholderAPI]

commands:
   sw:
   setswlobby:
   sw1:
   sw2:
   sw3: 
   sw4:
   sw5:
   spec:
    description: Assistir um jogador da partida
    usage: /spec <player>
   specgui:
    description: Abrir menu de espectadores
    
   
   
   